#' Add column from patient data
#'
#' @param df A dataframe produced by clean_thermograms()
#' @param df_patient Patient data file generated by load_patient
#' @param column_name Column to be added
#'
#' @return Returns a dataframe
#' @importFrom magrittr %>%
#'
add_patient_column <- function(df, df_patient, column_name){
  df <- df %>%
    dplyr::left_join(dplyr::distinct(df_patient, `Patient code`, .keep_all = TRUE) %>%
                       dplyr::select('Patient code', all_of(column_name)), by=c('Patient'='Patient code'))
  return(df)
}
