#' Add column from summary data
#'
#' @param df A dataframe produced by clean_thermograms()
#' @param df_summary Summary data file generated by generate_summary
#' @param column_name Column to be added
#'
#' @return Returns a dataframe
#' @importFrom magrittr %>%
#'
add_summary_column <- function(df, df_summary, column_name){
  df <- df %>% dplyr::mutate(df_summary[!!column_name])
  return(df)
}
